// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catagent} from '../models';
import {cat} from '../models';

export function CancelCatTurn(arg1:catagent.CancelCatTurnRequest):Promise<void>;

export function CreateCatConversation(arg1:cat.CreateConversationRequest):Promise<cat.Conversation>;

export function CreateCatProject(arg1:cat.CreateProjectRequest):Promise<cat.CreateProjectResult>;

export function DeleteCatConversation(arg1:string):Promise<void>;

export function DeleteCatProject(arg1:cat.DeleteProjectRequest):Promise<void>;

export function GetCatConversation(arg1:string):Promise<cat.ConversationDetail>;

export function GetCatStatus():Promise<catagent.Status>;

export function ListCatConversations():Promise<Array<cat.Conversation>>;

export function ListCatModels(arg1:string):Promise<Array<catagent.Model>>;

export function ListCatProjects():Promise<Array<cat.Project>>;

export function ListCatThinkLevels(arg1:string):Promise<Array<catagent.ThinkLevel>>;

export function RecheckCat():Promise<catagent.Status>;

export function RenameCatProject(arg1:cat.RenameProjectRequest):Promise<cat.Project>;

export function SendCatMessage(arg1:cat.SendMessageRequest):Promise<cat.SendMessageResult>;
