// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catagent} from '../models';
import {cat} from '../models';
import {store} from '../models';

export function CancelCatTurn(arg1:catagent.CancelCatTurnRequest):Promise<void>;

export function CreateCatConversation(arg1:cat.CreateConversationRequest):Promise<store.CatConversation>;

export function CreateCatProject(arg1:cat.CreateProjectRequest):Promise<cat.CreateProjectResult>;

export function DeleteCatConversation(arg1:string):Promise<void>;

export function DeleteCatProject(arg1:cat.DeleteProjectRequest):Promise<void>;

export function GetCatConversation(arg1:string):Promise<cat.ConversationDetail>;

export function GetCatStatus():Promise<catagent.Status>;

export function ListCatConversations():Promise<Array<store.CatConversation>>;

export function ListCatFiles(arg1:cat.ListFilesRequest):Promise<cat.ListFilesResult>;

export function ListCatModels(arg1:string):Promise<Array<catagent.Model>>;

export function ListCatProjects():Promise<Array<cat.Project>>;

export function ListCatThinkLevels(arg1:string):Promise<Array<catagent.ThinkLevel>>;

export function RecheckCat():Promise<catagent.Status>;

export function ReadCatFile(arg1:cat.ReadFileRequest):Promise<cat.ReadFileResult>;

export function RelocateCatProject(arg1:cat.RelocateProjectRequest):Promise<cat.Project>;

export function RenameCatProject(arg1:cat.RenameProjectRequest):Promise<cat.Project>;

export function RevealCatConversationFolder(arg1:cat.RevealConversationFolderRequest):Promise<void>;

export function RevealCatProject(arg1:cat.RevealProjectRequest):Promise<void>;

export function SendCatMessage(arg1:cat.SendMessageRequest):Promise<cat.SendMessageResult>;

export function WriteCatFile(arg1:cat.WriteFileRequest):Promise<cat.WriteFileResult>;
