// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelCatTurn(arg1) {
  return window['go']['app']['CatService']['CancelCatTurn'](arg1);
}

export function CreateCatConversation(arg1) {
  return window['go']['app']['CatService']['CreateCatConversation'](arg1);
}

export function CreateCatProject(arg1) {
  return window['go']['app']['CatService']['CreateCatProject'](arg1);
}

export function DeleteCatConversation(arg1) {
  return window['go']['app']['CatService']['DeleteCatConversation'](arg1);
}

export function DeleteCatProject(arg1) {
  return window['go']['app']['CatService']['DeleteCatProject'](arg1);
}

export function GetCatConversation(arg1) {
  return window['go']['app']['CatService']['GetCatConversation'](arg1);
}

export function GetCatStatus() {
  return window['go']['app']['CatService']['GetCatStatus']();
}

export function ListCatConversations() {
  return window['go']['app']['CatService']['ListCatConversations']();
}

export function ListCatFiles(arg1) {
  return window['go']['app']['CatService']['ListCatFiles'](arg1);
}

export function ListCatModels(arg1) {
  return window['go']['app']['CatService']['ListCatModels'](arg1);
}

export function ListCatProjects() {
  return window['go']['app']['CatService']['ListCatProjects']();
}

export function ListCatThinkLevels(arg1) {
  return window['go']['app']['CatService']['ListCatThinkLevels'](arg1);
}

export function RecheckCat() {
  return window['go']['app']['CatService']['RecheckCat']();
}

export function ReadCatFile(arg1) {
  return window['go']['app']['CatService']['ReadCatFile'](arg1);
}

export function RelocateCatProject(arg1) {
  return window['go']['app']['CatService']['RelocateCatProject'](arg1);
}

export function RenameCatProject(arg1) {
  return window['go']['app']['CatService']['RenameCatProject'](arg1);
}

export function RevealCatConversationFolder(arg1) {
  return window['go']['app']['CatService']['RevealCatConversationFolder'](arg1);
}

export function RevealCatProject(arg1) {
  return window['go']['app']['CatService']['RevealCatProject'](arg1);
}

export function SendCatMessage(arg1) {
  return window['go']['app']['CatService']['SendCatMessage'](arg1);
}

export function WriteCatFile(arg1) {
  return window['go']['app']['CatService']['WriteCatFile'](arg1);
}
