// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {catagent} from '../models';
import {cat} from '../models';

export function CancelCatTurn(arg1:string):Promise<void>;

export function CreateCatConversation(arg1:cat.CreateConversationRequest):Promise<cat.Conversation>;

export function DeleteCatConversation(arg1:string):Promise<void>;

export function GetCatConversation(arg1:string):Promise<cat.ConversationDetail>;

export function GetCatStatus():Promise<catagent.Status>;

export function ListCatConversations():Promise<Array<cat.Conversation>>;

export function ListCatModels(arg1:string):Promise<Array<catagent.Model>>;

export function ListCatThinkLevels(arg1:string):Promise<Array<catagent.ThinkLevel>>;

export function RecheckCat():Promise<catagent.Status>;

export function SendCatMessage(arg1:cat.SendMessageRequest):Promise<cat.SendMessageResult>;
