// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePreset(arg1) {
  return window['go']['app']['ConvertService']['DeletePreset'](arg1);
}

export function ListPresets() {
  return window['go']['app']['ConvertService']['ListPresets']();
}

export function SavePreset(arg1) {
  return window['go']['app']['ConvertService']['SavePreset'](arg1);
}

export function Submit(arg1, arg2, arg3) {
  return window['go']['app']['ConvertService']['Submit'](arg1, arg2, arg3);
}
