// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {convert} from '../models';
import {task} from '../models';
import {store} from '../models';
import {ffmpeg} from '../models';

export function AddSources(arg1:Array<string>):Promise<Array<convert.AddSourceResult>>;

export function CheckSources(arg1:Array<string>):Promise<Array<convert.SourcePathCheck>>;

export function DeletePreset(arg1:string):Promise<void>;

export function DeleteRecords(arg1:Array<string>,arg2:boolean):Promise<task.DeleteResult>;

export function DeleteSource(arg1:string,arg2:boolean):Promise<task.DeleteResult>;

export function GetRecordThumbnail(arg1:string):Promise<string>;

export function GetSource(arg1:string):Promise<convert.ConvertSourceEntry>;

export function GetSourcePreviewURL(arg1:string):Promise<convert.PreviewURL>;

export function GetSourceThumbnail(arg1:string):Promise<string>;

export function ListPresets():Promise<Array<convert.Preset>>;

export function ListSourceRecords(arg1:string,arg2:number,arg3:number):Promise<store.TaskPage>;

export function ListSources(arg1:convert.ConvertSourceFilter):Promise<convert.ConvertSourcePage>;

export function OpenSourceWithSystem(arg1:string):Promise<void>;

export function PreviewOutputName(arg1:string,arg2:ffmpeg.ConvertOptions,arg3:string):Promise<string>;

export function Reconvert(arg1:string):Promise<store.Task>;

export function RevealRecord(arg1:string):Promise<void>;

export function RevealSource(arg1:string):Promise<void>;

export function SavePreset(arg1:convert.Preset):Promise<convert.Preset>;

export function SearchSources(arg1:convert.ConvertSearchFilter):Promise<convert.ConvertSourcePage>;

export function Submit(arg1:Array<string>,arg2:ffmpeg.ConvertOptions,arg3:string):Promise<Array<store.Task>>;

export function SubmitSources(arg1:convert.ConvertSubmitRequest):Promise<Array<store.Task>>;
