// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSources(arg1) {
  return window['go']['app']['ConvertService']['AddSources'](arg1);
}

export function CheckSources(arg1) {
  return window['go']['app']['ConvertService']['CheckSources'](arg1);
}

export function DeletePreset(arg1) {
  return window['go']['app']['ConvertService']['DeletePreset'](arg1);
}

export function DeleteRecords(arg1, arg2) {
  return window['go']['app']['ConvertService']['DeleteRecords'](arg1, arg2);
}

export function DeleteSource(arg1, arg2) {
  return window['go']['app']['ConvertService']['DeleteSource'](arg1, arg2);
}

export function GetRecordThumbnail(arg1) {
  return window['go']['app']['ConvertService']['GetRecordThumbnail'](arg1);
}

export function GetSource(arg1) {
  return window['go']['app']['ConvertService']['GetSource'](arg1);
}

export function GetSourcePreviewURL(arg1) {
  return window['go']['app']['ConvertService']['GetSourcePreviewURL'](arg1);
}

export function GetSourceThumbnail(arg1) {
  return window['go']['app']['ConvertService']['GetSourceThumbnail'](arg1);
}

export function ListPresets() {
  return window['go']['app']['ConvertService']['ListPresets']();
}

export function ListSourceRecords(arg1, arg2, arg3) {
  return window['go']['app']['ConvertService']['ListSourceRecords'](arg1, arg2, arg3);
}

export function ListSources(arg1) {
  return window['go']['app']['ConvertService']['ListSources'](arg1);
}

export function OpenSourceWithSystem(arg1) {
  return window['go']['app']['ConvertService']['OpenSourceWithSystem'](arg1);
}

export function PreviewOutputName(arg1, arg2, arg3) {
  return window['go']['app']['ConvertService']['PreviewOutputName'](arg1, arg2, arg3);
}

export function Reconvert(arg1) {
  return window['go']['app']['ConvertService']['Reconvert'](arg1);
}

export function RevealRecord(arg1) {
  return window['go']['app']['ConvertService']['RevealRecord'](arg1);
}

export function RevealSource(arg1) {
  return window['go']['app']['ConvertService']['RevealSource'](arg1);
}

export function SavePreset(arg1) {
  return window['go']['app']['ConvertService']['SavePreset'](arg1);
}

export function SearchSources(arg1) {
  return window['go']['app']['ConvertService']['SearchSources'](arg1);
}

export function Submit(arg1, arg2, arg3) {
  return window['go']['app']['ConvertService']['Submit'](arg1, arg2, arg3);
}

export function SubmitSources(arg1) {
  return window['go']['app']['ConvertService']['SubmitSources'](arg1);
}
