// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {convert} from '../models';
import {ffmpeg} from '../models';
import {store} from '../models';

export function DeletePreset(arg1:string):Promise<void>;

export function ListPresets():Promise<Array<convert.Preset>>;

export function SavePreset(arg1:convert.Preset):Promise<convert.Preset>;

export function Submit(arg1:Array<string>,arg2:ffmpeg.ConvertOptions,arg3:string):Promise<Array<store.Task>>;
