// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {doc} from '../models';

export function ConvertToPDF(arg1:Array<string>,arg2:string):Promise<Array<store.Task>>;

export function GetDocCapabilities():Promise<doc.DocCapabilities>;

export function ListRecentPDFs(arg1:number):Promise<Array<doc.PDFFile>>;

export function OpenPDF(arg1:string):Promise<doc.PDFSource>;

export function ReadPDFChunk(arg1:string,arg2:number,arg3:number):Promise<doc.PDFChunk>;

export function RemoveRecentPDFs(arg1:Array<string>):Promise<void>;
