// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddDocSources(arg1) {
  return window['go']['app']['DocService']['AddDocSources'](arg1);
}

export function CancelDocComponentInstall() {
  return window['go']['app']['DocService']['CancelDocComponentInstall']();
}

export function ConvertToPDF(arg1, arg2) {
  return window['go']['app']['DocService']['ConvertToPDF'](arg1, arg2);
}

export function GetDocCapabilities() {
  return window['go']['app']['DocService']['GetDocCapabilities']();
}

export function GetDocComponentStatus() {
  return window['go']['app']['DocService']['GetDocComponentStatus']();
}

export function GetFormatMatrix() {
  return window['go']['app']['DocService']['GetFormatMatrix']();
}

export function InstallDocComponent(arg1) {
  return window['go']['app']['DocService']['InstallDocComponent'](arg1);
}

export function ListDocSources(arg1) {
  return window['go']['app']['DocService']['ListDocSources'](arg1);
}

export function ListRecentPDFs(arg1) {
  return window['go']['app']['DocService']['ListRecentPDFs'](arg1);
}

export function OpenPDF(arg1) {
  return window['go']['app']['DocService']['OpenPDF'](arg1);
}

export function ReadPDFChunk(arg1, arg2, arg3) {
  return window['go']['app']['DocService']['ReadPDFChunk'](arg1, arg2, arg3);
}

export function RecheckDocComponent() {
  return window['go']['app']['DocService']['RecheckDocComponent']();
}

export function RemoveRecentPDFs(arg1) {
  return window['go']['app']['DocService']['RemoveRecentPDFs'](arg1);
}

export function SearchDocSources(arg1) {
  return window['go']['app']['DocService']['SearchDocSources'](arg1);
}

export function SubmitDocConvert(arg1) {
  return window['go']['app']['DocService']['SubmitDocConvert'](arg1);
}
