// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {doc} from '../models';
import {store} from '../models';
import {convert} from '../models';

export function AddDocSources(arg1:Array<string>):Promise<Array<doc.AddDocSourceResult>>;

export function CancelDocComponentInstall():Promise<void>;

export function CancelDocPreview(arg1:string):Promise<void>;

export function ConvertToPDF(arg1:Array<string>,arg2:string):Promise<Array<store.Task>>;

export function GetDocCapabilities():Promise<doc.DocCapabilities>;

export function GetDocComponentStatus():Promise<doc.DocComponentStatus>;

export function GetDocPreview(arg1:doc.DocPreviewRequest):Promise<doc.DocPreview>;

export function GetFormatMatrix():Promise<doc.DocFormatMatrix>;

export function InstallDocComponent(arg1:string):Promise<doc.DocComponentStatus>;

export function ListDocSources(arg1:convert.ConvertSourceFilter):Promise<doc.DocSourcePage>;

export function ListRecentPDFs(arg1:number):Promise<Array<doc.PDFFile>>;

export function OpenPDF(arg1:string):Promise<doc.PDFSource>;

export function ReadPDFChunk(arg1:string,arg2:number,arg3:number):Promise<doc.PDFChunk>;

export function RecheckDocComponent():Promise<doc.DocComponentStatus>;

export function RemoveRecentPDFs(arg1:Array<string>):Promise<void>;

export function SearchDocSources(arg1:convert.ConvertSearchFilter):Promise<doc.DocSourcePage>;

export function SubmitDocConvert(arg1:doc.DocSubmitRequest):Promise<convert.ConvertSubmitResult>;
