// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertToPDF(arg1, arg2) {
  return window['go']['app']['DocService']['ConvertToPDF'](arg1, arg2);
}

export function GetDocCapabilities() {
  return window['go']['app']['DocService']['GetDocCapabilities']();
}

export function ListRecentPDFs(arg1) {
  return window['go']['app']['DocService']['ListRecentPDFs'](arg1);
}

export function OpenPDF(arg1) {
  return window['go']['app']['DocService']['OpenPDF'](arg1);
}

export function ReadPDFChunk(arg1, arg2, arg3) {
  return window['go']['app']['DocService']['ReadPDFChunk'](arg1, arg2, arg3);
}

export function RemoveRecentPDFs(arg1) {
  return window['go']['app']['DocService']['RemoveRecentPDFs'](arg1);
}
