// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteProject(arg1) {
  return window['go']['app']['EditService']['DeleteProject'](arg1);
}

export function Export(arg1, arg2) {
  return window['go']['app']['EditService']['Export'](arg1, arg2);
}

export function GetPreviewURL(arg1) {
  return window['go']['app']['EditService']['GetPreviewURL'](arg1);
}

export function ListProjects(arg1) {
  return window['go']['app']['EditService']['ListProjects'](arg1);
}

export function LoadProject(arg1) {
  return window['go']['app']['EditService']['LoadProject'](arg1);
}

export function SaveProject(arg1) {
  return window['go']['app']['EditService']['SaveProject'](arg1);
}

export function ValidateProject(arg1) {
  return window['go']['app']['EditService']['ValidateProject'](arg1);
}
