// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {edit} from '../models';
import {store} from '../models';

export function DeleteProject(arg1:string):Promise<void>;

export function Export(arg1:edit.EditProject,arg2:edit.EditExportOptions):Promise<store.Task>;

export function GetPreviewURL(arg1:string):Promise<edit.PreviewURL>;

export function ListProjects(arg1:number):Promise<Array<edit.EditProjectMeta>>;

export function LoadProject(arg1:string):Promise<edit.LoadedProject>;

export function SaveProject(arg1:edit.EditProject):Promise<edit.EditProjectMeta>;

export function ValidateProject(arg1:edit.EditProject):Promise<edit.EditPlan>;
