// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {jsontool} from '../models';

export function Compare(arg1:jsontool.CompareRequest):Promise<jsontool.CompareResponse>;

export function Format(arg1:jsontool.FormatRequest):Promise<jsontool.FormatResponse>;

export function Validate(arg1:jsontool.ValidateRequest):Promise<jsontool.ValidateResponse>;
