// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compare(arg1) {
  return window['go']['app']['JsonService']['Compare'](arg1);
}

export function Format(arg1) {
  return window['go']['app']['JsonService']['Format'](arg1);
}

export function Validate(arg1) {
  return window['go']['app']['JsonService']['Validate'](arg1);
}
