// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {langasr} from '../models';
import {lang} from '../models';
import {store} from '../models';

export function CancelLangAsrInstall():Promise<void>;

export function ExportSubtitleCues(arg1:lang.ExportSubtitleRequest):Promise<lang.ExportSubtitleResult>;

export function GetLangAsrStatus():Promise<langasr.Status>;

export function InstallLangAsr(arg1:string):Promise<langasr.Status>;

export function RecheckLangAsr():Promise<langasr.Status>;

export function SubmitSpeechToSubtitle(arg1:lang.SpeechToSubtitleRequest):Promise<Array<store.Task>>;
