// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelLangAsrInstall() {
  return window['go']['app']['LangService']['CancelLangAsrInstall']();
}

export function ExportSubtitleCues(arg1) {
  return window['go']['app']['LangService']['ExportSubtitleCues'](arg1);
}

export function GetLangAsrStatus() {
  return window['go']['app']['LangService']['GetLangAsrStatus']();
}

export function InstallLangAsr(arg1) {
  return window['go']['app']['LangService']['InstallLangAsr'](arg1);
}

export function RecheckLangAsr() {
  return window['go']['app']['LangService']['RecheckLangAsr']();
}

export function SubmitSpeechToSubtitle(arg1) {
  return window['go']['app']['LangService']['SubmitSpeechToSubtitle'](arg1);
}
