// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPushURL(arg1) {
  return window['go']['app']['LiveService']['CheckPushURL'](arg1);
}

export function GetCaptureCapabilities() {
  return window['go']['app']['LiveService']['GetCaptureCapabilities']();
}

export function ListCaptureSources() {
  return window['go']['app']['LiveService']['ListCaptureSources']();
}

export function ListScreens() {
  return window['go']['app']['LiveService']['ListScreens']();
}

export function StartFilePush(arg1) {
  return window['go']['app']['LiveService']['StartFilePush'](arg1);
}

export function StartScreenPush(arg1) {
  return window['go']['app']['LiveService']['StartScreenPush'](arg1);
}
