// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {live} from '../models';
import {store} from '../models';

export function CheckPushURL(arg1:string):Promise<live.PushURLInfo>;

export function StartFilePush(arg1:live.FilePushRequest):Promise<store.Task>;
