// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPushURL(arg1) {
  return window['go']['app']['LiveService']['CheckPushURL'](arg1);
}

export function StartFilePush(arg1) {
  return window['go']['app']['LiveService']['StartFilePush'](arg1);
}
