// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {media} from '../models';

export function ListRecent(arg1:number):Promise<Array<store.MediaInfo>>;

export function Probe(arg1:Array<string>):Promise<Array<store.MediaInfo>>;

export function RemoveRecent(arg1:Array<string>):Promise<void>;

export function Thumbnail(arg1:string,arg2:number,arg3:number):Promise<media.Thumb>;
