// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListRecent(arg1) {
  return window['go']['app']['MediaService']['ListRecent'](arg1);
}

export function Probe(arg1) {
  return window['go']['app']['MediaService']['Probe'](arg1);
}

export function RemoveRecent(arg1) {
  return window['go']['app']['MediaService']['RemoveRecent'](arg1);
}

export function Thumbnail(arg1, arg2, arg3) {
  return window['go']['app']['MediaService']['Thumbnail'](arg1, arg2, arg3);
}
