// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFFmpegInstall() {
  return window['go']['app']['SystemService']['CancelFFmpegInstall']();
}

export function GetFFmpegStatus() {
  return window['go']['app']['SystemService']['GetFFmpegStatus']();
}

export function GetInstallOptions() {
  return window['go']['app']['SystemService']['GetInstallOptions']();
}

export function GetSettings() {
  return window['go']['app']['SystemService']['GetSettings']();
}

export function InstallFFmpeg(arg1) {
  return window['go']['app']['SystemService']['InstallFFmpeg'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['app']['SystemService']['PickDirectory'](arg1);
}

export function RecheckFFmpeg() {
  return window['go']['app']['SystemService']['RecheckFFmpeg']();
}

export function RevealInFolder(arg1) {
  return window['go']['app']['SystemService']['RevealInFolder'](arg1);
}

export function SetFFmpegPath(arg1) {
  return window['go']['app']['SystemService']['SetFFmpegPath'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['SystemService']['UpdateSettings'](arg1);
}
