// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';

export function CancelFFmpegInstall():Promise<void>;

export function GetFFmpegStatus():Promise<system.FFmpegStatus>;

export function GetSettings():Promise<system.Settings>;

export function InstallFFmpeg(arg1:string):Promise<system.InstallTask>;

export function RecheckFFmpeg():Promise<system.FFmpegStatus>;

export function SetFFmpegPath(arg1:string):Promise<system.FFmpegStatus>;

export function UpdateSettings(arg1:system.Settings):Promise<void>;
