// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelFFmpegInstall() {
  return window['go']['app']['SystemService']['CancelFFmpegInstall']();
}

export function GetEncoderPreference() {
  return window['go']['app']['SystemService']['GetEncoderPreference']();
}

export function GetEncoderPreferenceInfo() {
  return window['go']['app']['SystemService']['GetEncoderPreferenceInfo']();
}

export function GetFFmpegStatus() {
  return window['go']['app']['SystemService']['GetFFmpegStatus']();
}

export function GetInstallOptions() {
  return window['go']['app']['SystemService']['GetInstallOptions']();
}

export function GetSettings() {
  return window['go']['app']['SystemService']['GetSettings']();
}

export function GetStorageDirs() {
  return window['go']['app']['SystemService']['GetStorageDirs']();
}

export function InstallFFmpeg(arg1) {
  return window['go']['app']['SystemService']['InstallFFmpeg'](arg1);
}

export function ListEncoderDevices() {
  return window['go']['app']['SystemService']['ListEncoderDevices']();
}

export function OpenStorageFolder(arg1) {
  return window['go']['app']['SystemService']['OpenStorageFolder'](arg1);
}

export function PickDirectory(arg1) {
  return window['go']['app']['SystemService']['PickDirectory'](arg1);
}

export function PickFiles(arg1, arg2) {
  return window['go']['app']['SystemService']['PickFiles'](arg1, arg2);
}

export function RecheckFFmpeg() {
  return window['go']['app']['SystemService']['RecheckFFmpeg']();
}

export function RefreshEncoderDevices() {
  return window['go']['app']['SystemService']['RefreshEncoderDevices']();
}

export function RevealInFolder(arg1) {
  return window['go']['app']['SystemService']['RevealInFolder'](arg1);
}

export function SetEncoderPreference(arg1) {
  return window['go']['app']['SystemService']['SetEncoderPreference'](arg1);
}

export function SetFFmpegPath(arg1) {
  return window['go']['app']['SystemService']['SetFFmpegPath'](arg1);
}

export function SetStorageDirs(arg1) {
  return window['go']['app']['SystemService']['SetStorageDirs'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['SystemService']['UpdateSettings'](arg1);
}
