// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {store} from '../models';

export function CancelFFmpegInstall():Promise<void>;

export function GetFFmpegStatus():Promise<system.FFmpegStatus>;

export function GetInstallOptions():Promise<system.InstallOptions>;

export function GetSettings():Promise<system.Settings>;

export function InstallFFmpeg(arg1:string):Promise<store.Task>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickFiles(arg1:system.FileFilter,arg2:boolean):Promise<Array<string>>;

export function RecheckFFmpeg():Promise<system.FFmpegStatus>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SetFFmpegPath(arg1:string):Promise<system.FFmpegStatus>;

export function UpdateSettings(arg1:system.Settings):Promise<void>;
