// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {system} from '../models';
import {store} from '../models';

export function CancelFFmpegInstall():Promise<void>;

export function GetEncoderPreference():Promise<string>;

export function GetEncoderPreferenceInfo():Promise<system.EncoderPreferenceInfo>;

export function GetFFmpegStatus():Promise<system.FFmpegStatus>;

export function GetInstallOptions():Promise<system.InstallOptions>;

export function GetSettings():Promise<system.Settings>;

export function GetStorageDirs():Promise<system.StorageDirs>;

export function InstallFFmpeg(arg1:string):Promise<store.Task>;

export function ListEncoderDevices():Promise<system.EncoderDeviceList>;

export function OpenStorageFolder(arg1:string):Promise<void>;

export function PickDirectory(arg1:string):Promise<string>;

export function PickFiles(arg1:system.FileFilter,arg2:boolean):Promise<Array<string>>;

export function RecheckFFmpeg():Promise<system.FFmpegStatus>;

export function RefreshEncoderDevices():Promise<system.EncoderDeviceList>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:Array<system.FileFilter>):Promise<string>;

export function SetEncoderPreference(arg1:string):Promise<void>;

export function SetFFmpegPath(arg1:string):Promise<system.FFmpegStatus>;

export function SetStorageDirs(arg1:system.StorageDirsUpdate):Promise<system.StorageDirs>;

export function UpdateSettings(arg1:system.Settings):Promise<void>;
