// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFFmpegStatus() {
  return window['go']['app']['SystemService']['GetFFmpegStatus']();
}

export function GetSettings() {
  return window['go']['app']['SystemService']['GetSettings']();
}

export function RecheckFFmpeg() {
  return window['go']['app']['SystemService']['RecheckFFmpeg']();
}

export function SetFFmpegPath(arg1) {
  return window['go']['app']['SystemService']['SetFFmpegPath'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['SystemService']['UpdateSettings'](arg1);
}
