// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {task} from '../models';
import {store} from '../models';
import {convert} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function CheckPaths(arg1:Array<string>):Promise<Array<task.TaskPathCheck>>;

export function ClearFinished():Promise<void>;

export function Get(arg1:string):Promise<store.Task>;

export function GetLog(arg1:string,arg2:number):Promise<string>;

export function GetPreviewURL(arg1:string,arg2:string):Promise<convert.PreviewURL>;

export function HideFinishedInTaskCenter():Promise<number>;

export function List(arg1:store.TaskFilter):Promise<store.TaskPage>;

export function ListActive():Promise<Array<store.Task>>;

export function OpenWithSystem(arg1:string,arg2:string):Promise<void>;

export function Remove(arg1:Array<string>,arg2:boolean):Promise<void>;

export function Retry(arg1:string):Promise<store.Task>;

export function UnhideInTaskCenter(arg1:Array<string>):Promise<void>;
