// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel(arg1) {
  return window['go']['app']['TaskService']['Cancel'](arg1);
}

export function ClearFinished() {
  return window['go']['app']['TaskService']['ClearFinished']();
}

export function Get(arg1) {
  return window['go']['app']['TaskService']['Get'](arg1);
}

export function GetLog(arg1, arg2) {
  return window['go']['app']['TaskService']['GetLog'](arg1, arg2);
}

export function List(arg1) {
  return window['go']['app']['TaskService']['List'](arg1);
}

export function ListActive() {
  return window['go']['app']['TaskService']['ListActive']();
}

export function Remove(arg1, arg2) {
  return window['go']['app']['TaskService']['Remove'](arg1, arg2);
}

export function Retry(arg1) {
  return window['go']['app']['TaskService']['Retry'](arg1);
}
