// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Cancel(arg1:string):Promise<void>;

export function ClearFinished():Promise<void>;

export function Get(arg1:string):Promise<store.Task>;

export function GetLog(arg1:string,arg2:number):Promise<string>;

export function List(arg1:store.TaskFilter):Promise<store.TaskPage>;

export function ListActive():Promise<Array<store.Task>>;

export function Remove(arg1:Array<string>,arg2:boolean):Promise<void>;

export function Retry(arg1:string):Promise<store.Task>;
