// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetLicenseText(arg1) {
  return window['go']['main']['App']['GetLicenseText'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Steamdom(arg1, arg2) {
  return window['go']['main']['App']['Steamdom'](arg1, arg2);
}
