// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppVersion():Promise<string>;

export function GetLicenseText(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Steamdom(arg1:string,arg2:string):Promise<void>;
